version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - TZ=ASIA/SEOUL